nodeLinker: node-modules

packageExtensions:
  lwc-webpack-plugin@*:
    dependencies:
      "@babel/core": "*"
      webpack: "*"
      loader-utils: "^2.0.0"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
